### ISSUE TITLE
Get/reset fetchmode on getASSOC()

### ISSUE THREAD

**Issue by sebstyle** [nbari/DALMP#10]
The getASSOC() method changes $this->fetchMode to MYSQLI_ASSOC;
If it was previously set to something other than that the next operation will return unexpected results..

```
->FetchMode('NUM');
->getASSOC($query);
// Expected: assoc array (obviously)
->getAll($query);
// Expected: numeric array
// Returned: assoc array (unexpected)
```
Might be a good idea to check if fetchmode needs to be reset when getASSOC() is done..
```
    public function getASSOC($sql)
    {
        if ($this->debug) $this->debug->log(__METHOD__, "sql: $sql");
        if ($this->Execute($sql)) {
            $cols = $this->numOfFields;
            if ($cols < 2) {
                return false;
            }
            // Get previous fetchmode
            $reset = ($this->fetchMode != MYSQLI_ASSOC) ? $this->fetchMode : false;
            // Set current fetchmode
            $this->fetchMode = MYSQLI_ASSOC;
            $assoc = array();
            if ($cols == 2) {
                while ($row = $this->_fetch()) {
                    $assoc[reset($row)] = next($row);
                }
            } else {
                while ($row = $this->_fetch()) {
                    $assoc[reset($row)] = array_slice($row, 1);
                }
            }
            $this->Close();
            // Reset to previous fetchmode
            if ($reset !== false) { $this->fetchMode = $reset; }

            return $assoc;
        } else {
            return false;
        }
    }
```

**Comment by nbari** [comment]
I think that will make things more complicated to fix code not properly using the correct method, at the end is more an implementation issue than a bug/issue with the code.

**Comment by sebstyle** [comment]
I would argue that current usage of getASSOC() is metaphorically like: 
"Flipping the light switch in your living room also flushes the toilet"
And I would have an issue with my contractor if he designed my house that way ;)

If methods make these kind of unrelated/unpredictable class state changes one might as well make chaining FetchMode() mandatory on each call because one can never be certain it is still set to what it was explicitly told to be.

Perhaps a note/warning in the documentation for getASSOC() would be an acceptable compromise.
Something along the lines of: Using getASSOC() automatically sets fetchmode to assoc..
