### ISSUE TITLE
DAL = Data Access Layer, not Database Abstraction Layer

### ISSUE THREAD

**Issue by Yousha** [nbari/DALMP#11]
**DAL = Data Access Layer**
https://en.wikipedia.org/wiki/Data_access_layer

> **Data access layer** (DAL) in computer software, is a layer of a computer program which provides simplified access to data stored in persistent storage of some kind, such as an entity-relational database. 

**DBAL = DataBase Abstraction Layer**
https://en.wikipedia.org/wiki/Database_abstraction_layer

>  **Database abstraction layer** is an application programming interface which unifies the communication between a computer application and databases such as SQL Server, DB2, MySQL, PostgreSQL, Oracle or SQLite.

So this project is a **DBAL**, not DAL.

**Comment by nbari** [comment]
hi @Yousha the title of the project says:

    DALMP
    Database Abstraction Layer for MySQL using PHP

Basically:
    
     D - Database
     A - Abstraction
     L - Layer
     M - MySQL
     P - PHP

Please don't confuse the name with the purpose of the application.


By following your logic just imagine the confusion the  "Doctrine" project may be doing:

    doctrine
    a belief or set of beliefs held and taught by a Church, political party, or other group.

So just take it easy, at the end are only names that in some cases they are not even close or match the purpose of the applications.

**Comment by Yousha** [comment]
**That logic is true**(mine, wiki whatever).
But you could say: **Its just a Name**
Instead of questioning the principles/basics

Anyway GL.
